// 2025-03-30-angular/02-social-network-client/src/app/components/posts/post/post.component.ts
import { Component, input, output } from '@angular/core';
import { Post } from '../../../models/post/post.model';
import { ProfileService } from '../../../services/profile.service';
import { environment } from '../../../../environments/environment';

@Component({
  selector: 'app-post',
  imports: [],
  templateUrl: './post.component.html',
  styleUrl: './post.component.css'
})
export class PostComponent {

  constructor(
    public profileService: ProfileService
  ) {}

  post = input<Post>()
  deletedPost = output<string>()
  imageURL = `${environment.awsServerUrl}/${this.post()?.imageUrl}`

  async deleteMe() {
    try {
      this.profileService.deletePost(this.post()!.id)
      this.deletedPost.emit(this.post()!.id)
    } catch (error) {
      alert(error)
    }
  }
}

<div id="post">
    <div>{{post()?.title}}</div>
    <div>
        by {{post()?.user?.name}} on {{post()?.createdAt?.toLocaleString()}}
    </div>
    @if (post()?.imageUrl) {
        <div>
            <img [src]="imageURL" />
        </div>
    }
    <div>{{post()?.body}}</div>

    <button (click)="deleteMe()">Delete</button>
</div>

// 2025-01-12/social-network-client/src/components/posts/post/Post.tsx
import PostModel from '../../../models/post/Post';
import profile from '../../../services/profile';
import './Post.css'

interface PostProps {
    post: PostModel;
    isAllowActions?: boolean;
    remove?(id: string): void;
}

function Post({ post, isAllowActions, remove }: PostProps): JSX.Element {
    const { id, title, body, createdAt} = post
    const { name } = post.user

    async function deleteMe() {
        if(remove && confirm(`Are you sure you want to delete "${title}"`)) {
            try {
                await profile.remove(id)
                remove(id);
                // I was able to delete from the server,
                // this is the point to affect the UI
                // In other words, we need to change the state
            } catch (error) {
                alert(error)
            }
        }
    }
    
    return (
        <div className='Post'>
            <div>{title}</div>
            <div>
                by {name} at {createdAt}
            </div>
            <div>{body}</div>
            {isAllowActions && 
                <div>
                    <button>Edit</button>
                    <button onClick={deleteMe}>Delete</button>
                </div>
            }
        </div>
    )
}

export default Post;
