// 2025-03-30-angular/homework/frontend-angular/src/app/components/comments/new-comment/new-comment.component.ts
import { Component, input, output } from '@angular/core';
import { CommentsService } from '../../../services/comments.service';
import { PostComment } from '../../../models/comment/comment.model';

@Component({
  selector: 'app-new-comment',
  imports: [],
  templateUrl: './new-comment.component.html',
  styleUrl: './new-comment.component.css'
})
export class NewCommentComponent {

  constructor(
    public commentsService: CommentsService
  ) {}

  postId = input<string>()
  newComment = output<PostComment[]>()

  async submit() {
    try {
      const comments = await this.commentsService.createComment(this.postId()!, {body: 'Got a POST request to endpoint /comments/67e29063e641967c3e873ffe'})
      this.newComment.emit(comments)
    } catch (error) {
      
    }
  }
}

<div id='newComment'>
    <form (submit)="submit()">
        <textarea placeholder='Post your replay'></textarea>
        <button>Post replay</button>
    </form>
</div>

// 2025-01-14-add-comment-unfollow-hook-redux/social-network-client/src/components/comments/new-comment/NewComment.tsx
import { useForm } from 'react-hook-form';
import './NewComment.css'
import CommentDraft from '../../../models/comment/CommentDraft';
import CommentModel from '../../../models/comment/Comment';
import comments from '../../../services/comments';

interface newCommentProps {
    postId: string;
    onNewComment (newComment: CommentModel): void;
}

function NewComment({ postId, onNewComment }: newCommentProps): JSX.Element {
    const { register, handleSubmit, formState, reset } = useForm<CommentDraft>()

    async function submit(draft: CommentDraft) {
        try {
            const addedComment = await comments.addComment(postId, draft)
            onNewComment(addedComment);
            reset()
        } catch (error) {
            alert(error)
        }
    }

    return (
        <div className='NewComment'>
            <form onSubmit={handleSubmit(submit)}>
                <textarea placeholder='Post your replay' {...register('body', {
                    required: {
                        value: true,
                        message: "You must provide a replay"
                    },
                    minLength: {
                        value: 20,
                        message: "Replay must be 20 chars long"
                    }
                })}></textarea>
                <span className='error'>{formState.errors.body?.message}</span>
                <button>Replay</button>
            </form>
        </div>
    )
}

export default NewComment;
