// 2025-04-01-angular/01-social-network-client/src/app/components/posts/post/post.component.ts
import { Component, input, output } from '@angular/core';
import { Post } from '../../../models/post/post.model';
import { ProfileService } from '../../../services/profile.service';
import { environment } from '../../../../environments/environment';
import { PostCommentsComponent } from "../../comments/post-comments/post-comments.component";
import { PostComment } from '../../../models/comment/comment.model';
import { Router } from '@angular/router';

@Component({
  selector: 'app-post',
  imports: [PostCommentsComponent],
  templateUrl: './post.component.html',
  styleUrl: './post.component.css'
})
export class PostComponent {

  constructor(
    public profileService: ProfileService,
    public router: Router
  ) {}

  post = input<Post>()
  deletedPost = output<string>()
  commentsIsChange = output<PostComment[]>()
  commentsIsDelete = output<{commentId: string, postId: string}>()
  awsUrl = `${environment.awsServerUrl}/`

  async deleteMe() {
    try {
      this.profileService.deletePost(this.post()!.id)
      this.deletedPost.emit(this.post()!.id)
    } catch (error) {
      alert(error)
    }
  }

  async editMe() {
    this.router.navigate([`/edit/${this.post()!.id}`])
  }

  commentsChange(comments: PostComment[]) {
    this.commentsIsChange.emit(comments)
  }

  deleteComment(id: string) {
    this.commentsIsDelete.emit({commentId: id, postId: this.post()!.id})
  }
}

<div id="post">
    <div>{{post()?.title}}</div>
    <div>
        by {{post()?.user?.name}} on {{(post()?.createdAt)?.toLocaleString()}}
    </div>
    @if (post()?.imageUrl) {
        <div>
            <img src="{{ awsUrl + post()?.imageUrl }}" />
        </div>
    }
    <div>{{post()?.body}}</div>

    <button (click)="deleteMe()">Delete</button>
    <button (click)="editMe()">Edit</button>

    <app-post-comments
        [postId]="post()?.id"
        [comments]="post()?.comments"
        (commentsChange)="commentsChange($event)"
        (commentsDeleted)="deleteComment($event)"
    >
    </app-post-comments>
</div>

// 2025-01-12/homework/social-network-client/src/components/posts/post/Post.tsx
import { useNavigate } from 'react-router-dom';
import PostModel from '../../../models/post/Post';
import profile from '../../../services/profile';
import './Post.css'
import PostComments from '../../comments/post-comments/PostComments';

interface PostProps {
    post: PostModel;
    isAllowActions?: boolean;
    remove?(id: string): void;
}

function Post({ post, isAllowActions, remove }: PostProps): JSX.Element {
    const { id, title, body, createdAt, comments} = post
    const { name } = post.user
    const navigate = useNavigate()

    const formattedDate = new Date(createdAt).toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'short',
        day: 'numeric',
    });

    async function deleteMe() {
        if(remove && confirm(`Are you sure you want to delete "${title}"`)) {
            try {
                await profile.remove(id)
                remove(id);
                // I was able to delete from the server,
                // this is the point to affect the UI
                // In other words, we need to change the state
            } catch (error) {
                alert(error)
            }
        }
    }

    function editMe() {
        navigate(`/edit/${id}`)
    }
    
    return (
        <div className='Post'>
            <div>{title}</div>
            <div>
                by {name} on {formattedDate}
            </div>
            <div>{body}</div>
            {isAllowActions && 
                <div>
                    <button onClick={editMe}>Edit</button>
                    <button onClick={deleteMe}>Delete</button>
                </div>
            }
            <PostComments
                initialComments={comments}
                postId={id}
            />
        </div>
    )
}

export default Post;
