// 2025-03-04/homework/01-steimatzky-project/frontend/src/components/books/card/Card.tsx
import Book from '../../../models/book/Book';
import bookService from '../../../services/book';
import './Card.css';

interface PropsCard {
    book: Book
    deleteBookState: (bookId: string) => void;
}

function Card({ book, deleteBookState }: PropsCard): JSX.Element {

    async function deleteMe() {
        try {
            await bookService.deleteBook(book.id)
            deleteBookState(book.id)
        } catch (error) {
            alert(error)
        }
    }

    return (
        <div className='Card'>
            <h6>Book Name: {book.bookName} | Genre: {book.genre.name}</h6>
            <small>{book.summary}</small>
            <p>Price: {book.bookPrice}</p>
            <p>Stock: {book.stock}</p>
            <button onClick={deleteMe}>Delete Book</button>
        </div>
    )
}

export default Card;

// 2025-04-01-angular/homework/03-toys-r-us/frontend/src/app/components/games/card/card.component.ts
import { Component, input, output } from '@angular/core';
import { GamesService } from '../../../services/games.service';
import { Game } from '../../../models/games/game.model';

@Component({
  selector: 'app-card',
  imports: [],
  templateUrl: './card.component.html',
  styleUrl: './card.component.css'
})
export class CardComponent {

  constructor(
    public gamesService: GamesService
  ) {}

  game = input<Game>()
  gameDeleted = output<string>()


  async deleteMe() {
    try {
      await this.gamesService.delete(this.game()!.id)
      this.gameDeleted.emit(this.game()!.id)
    } catch (error) {
      alert(error)
    }
  }
}

<div id="gameCard">
  <div>
    <h2>{{ game()?.name }}</h2>
    <span>{{ game()?.target }}</span>
    <p>{{ game()?.price }}$</p>
    <small>{{game()?.description}}</small>
    <button (click)="deleteMe()">
      Delete
    </button>
  </div>
</div>
