// 2025-03-30-angular/02-social-network-client/src/app/components/layout/header/header.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';

@Component({
  selector: 'app-header',
  imports: [ RouterLink, RouterLinkActive ],
  templateUrl: './header.component.html',
  styleUrl: './header.component.css'
})
export class HeaderComponent {
  
}

<div id="header">
    <div>
        <h1><img src=""></h1>
    </div>
    <div>
        <nav>
            <a routerLink="/profile" routerLinkActive="active">Profile</a>
            <a routerLink="/feed" routerLinkActive="active">Feed</a>
        </nav>
    </div>
    <nav>
        Hello Bob
    </nav>
</div>

// 2025-01-12-props-routing-params-crud/social-network-client/src/components/layout/header/Header.tsx
import { NavLink } from 'react-router-dom';
import './Header.css'
import logoImage from '../../../assets/images/logo.png'

function Header(): JSX.Element {
    return (
        <div className='Header'>
            <div><img src={logoImage} alt="" /></div>
            <div>
                <nav>
                    <NavLink to="/profile">Profile</NavLink>
                    <NavLink to="/feed">Feed</NavLink>
                    <NavLink to="/search">Search</NavLink>
                </nav>
            </div>
            <nav>
                Hello Shay
                <a href="">Logout</a>
            </nav>
        </div>
    )
}

export default Header;
