// 2025-04-01-angular/homework/01-steimatzky/frontend/src/app/components/books/card/card.component.ts
import { Component, input, output } from '@angular/core';
import { Book } from '../../../models/books/book.model';
import { BooksService } from '../../../services/books.service';

@Component({
  selector: 'app-card',
  imports: [],
  templateUrl: './card.component.html',
  styleUrl: './card.component.css'
})
export class CardComponent {

  constructor(
    public booksService: BooksService
  ) {}

  book = input<Book>()
  bookDeleted = output<string>()


  async deleteMe() {
    try {
      await this.booksService.delete(this.book()!.id)
      this.bookDeleted.emit(this.book()!.id)
    } catch (error) {
      
    }
  }
}

<div class="book-card">
  <div class="book-details">
    <h2 class="book-title">{{ book()?.name }}</h2>
    <span class="book-genre">{{ book()?.gerne }}</span>
    <div class="book-price-container">
      <span class="book-price">{{ book()?.price }}$ </span>
      <span class="book-stock">
        {{ book()!.stock > 0 ? 'In stock (' + book()!.stock + ')' : 'Out of stock' }}
      </span>
    </div>
    <p class="book-summary">{{ book()?.summary }}</p>
    <button class="add-to-cart-btn" (click)="deleteMe()">
      Delete
    </button>
  </div>
</div>

// 2025-03-04/homework/01-steimatzky-project/frontend/src/components/books/card/Card.tsx
import Book from '../../../models/book/Book';
import bookService from '../../../services/book';
import './Card.css';

interface PropsCard {
    book: Book
    deleteBookState: (bookId: string) => void;
}

function Card({ book, deleteBookState }: PropsCard): JSX.Element {

    async function deleteMe() {
        try {
            await bookService.deleteBook(book.id)
            deleteBookState(book.id)
        } catch (error) {
            alert(error)
        }
    }

    return (
        <div className='Card'>
            <h6>Book Name: {book.bookName} | Genre: {book.genre.name}</h6>
            <small>{book.summary}</small>
            <p>Price: {book.bookPrice}</p>
            <p>Stock: {book.stock}</p>
            <button onClick={deleteMe}>Delete Book</button>
        </div>
    )
}

export default Card;
