// 2025-04-01-angular/homework/02-am-pm/frontend/src/app/components/products/card/card.component.ts
import { Component, input, output } from '@angular/core';
import { Product } from '../../../models/products/product.model';
import { ProductsService } from '../../../services/products.service';

@Component({
  selector: 'app-card',
  imports: [],
  templateUrl: './card.component.html',
  styleUrl: './card.component.css'
})
export class CardComponent {

  constructor(
    public productService: ProductsService
  ) {}

  product = input<Product>()
  productDeleted = output<string>()


  async deleteMe() {
    try {
      await this.productService.deleteProduct(this.product()!.id)
      this.productDeleted.emit(this.product()!.id)
    } catch (error) {
      alert(error)
    }
  }
}

<div class="book-card">
  <div class="book-details">
    <h2 class="book-title">{{ product()?.name }}</h2>
    <span class="book-genre">{{ product()?.category }}</span>
    <div class="book-price-container">
      <span class="book-price">{{ (product()?.prodDate) }} </span>
      <span class="book-price">{{ product()?.expireDate }} </span>
    </div>
    <p class="book-summary">{{ product()?.price }}$</p>

    <button class="add-to-cart-btn" (click)="deleteMe()">
      Delete
    </button>
  </div>
</div>

// 2025-03-04/homework/01-steimatzky-project/frontend/src/components/books/card/Card.tsx
import Book from '../../../models/book/Book';
import bookService from '../../../services/book';
import './Card.css';

interface PropsCard {
    book: Book
    deleteBookState: (bookId: string) => void;
}

function Card({ book, deleteBookState }: PropsCard): JSX.Element {

    async function deleteMe() {
        try {
            await bookService.deleteBook(book.id)
            deleteBookState(book.id)
        } catch (error) {
            alert(error)
        }
    }

    return (
        <div className='Card'>
            <h6>Book Name: {book.bookName} | Genre: {book.genre.name}</h6>
            <small>{book.summary}</small>
            <p>Price: {book.bookPrice}</p>
            <p>Stock: {book.stock}</p>
            <button onClick={deleteMe}>Delete Book</button>
        </div>
    )
}

export default Card;
